sudo: false
language: generic

addons:
  apt:
    packages:
      - luarocks

before_install:
  # Set path to include executables installed vialuarocks
  - PATH="${HOME}/.luarocks/bin:${PATH}"
  # Set lua path to include luarocks
  - eval "$(luarocks path)"
  # Ensure the newest versions of busted and luarocks are installed
  - luarocks install --local busted

install:
  - luarocks make --local rockspecs/panmeta-scm-0.rockspec

script:
  - busted tests
